/*
 * ! ICONCONFIG.JS @AUTHOR HUHAO @COMPANY BOCO
 */var iconConfig = {
	biaoshi : app
			+ '/arcGis/image/map/1353402145_Map-Marker-Push-Pin--Right-Pink.png',
	biaoshi1 : app
			+ '/arcGis/image/map/1353402145_Map-Marker-Push-Pin--Right-Pink1.png',
	biaoshi2 : app
			+ '/arcGis/image/map/1353402145_Map-Marker-Push-Pin--Right-Pink.png2',
	_2g3g : app + '/arcGis/image/map/siteblue.gif',
	_2g3g1 : app + '/arcGis/image/map/siteblue1.gif',
	_2g3g2 : app + '/arcGis/image/map/siteblue2.gif',
	_2g3g5 : app + '/arcGis/image/map/siteblue-blue-05.gif',
	_2g3g6 : app + '/arcGis/image/map/siteblue-green-06.gif',
	_2g3g7 : app + '/arcGis/image/map/siteblue-red-07.gif',
	_2g : app + '/arcGis/image/map/node/wire/icon-small-radio-bts-g.gif',
	_2g1 : app + '/arcGis/image/map/node/wire/icon-small-radio-bts-g1.png',
	_2g2 : app + '/arcGis/image/map/node/wire/icon-small-radio-bts-g2.png',
	_3g : app + '/arcGis/image/map/node/wire/icon-small-nodeb.gif',
	_3g1 : app + '/arcGis/image/map/node/wire/icon-small-nodeb1.gif',
	_3g2 : app + '/arcGis/image/map/node/wire/icon-small-nodeb2.gif',
	_3g5 : app + '/arcGis/image/map/node/wire/icon-small-nodeb-blue-05.gif',
	_3g6 : app + '/arcGis/image/map/node/wire/icon-small-nodeb-green-06.gif',
	_3g7 : app + '/arcGis/image/map/node/wire/icon-small-nodeb-red-07.gif',
	_3g8 : app + '/arcGis/image/map/node/wire/icon-small-nodeb-yellow-08.gif',
	tieta : app + '/arcGis/image/map/logic/bts_blue.png',
	tieta1 : app + '/arcGis/image/map/logic/bts_blue1.png',
	tieta2 : app + '/arcGis/image/map/logic/bts_blue2.png',
	tieta7 : app + '/arcGis/image/map/logic/bts_red_07.png',
	tieta5 : app + '/arcGis/image/map/logic/bts_blue_05.png',
	jiake : app + '/arcGis/image/map/node/inter/ONU.png',
	jiake1 : app + '/arcGis/image/map/node/inter/ONU1.png',
	jiake2 : app + '/arcGis/image/map/node/inter/ONU2.png',
	zhifangzhan : app + '/arcGis/image/map/node/wire/repeater.png',
	zhifangzhan1 : app + '/arcGis/image/map/node/wire/repeater1.png',
	zhifangzhan2 : app + '/arcGis/image/map/node/wire/repeater2.png',
	wlan : app + '/arcGis/image/map/node/wlan/AP.png',
	wlan1 : app + '/arcGis/image/map/node/wlan/AP1.png',
	wlan2 : app + '/arcGis/image/map/node/wlan/AP2.png',
	tianxian : app + '/arcGis/image/map/1353402396_Map-Marker-Flag--Azure.png',
	tianxian1 : app
			+ '/arcGis/image/map/1353402396_Map-Marker-Flag--Azure1.png',
	tianxian2 : app
			+ '/arcGis/image/map/1353402396_Map-Marker-Flag--Azure2.png',
	yuyinzhuanxian : app + '/arcGis/image/map/service/product.png',
	yuyinzhuanxian1 : app + '/arcGis/image/map/service/product1.png',
	yuyinzhuanxian2 : app + '/arcGis/image/map/service/product2.png',
	gprs : app + '/arcGis/image/map/node/gprs/gprsDNS.png',
	gprs1 : app + '/arcGis/image/map/node/gprs/gprsDNS1.png',
	gprs2 : app + '/arcGis/image/map/node/gprs/gprsDNS2.png',
	shujuzhuanxian : app + '/arcGis/image/map/logic/rnc.png',
	shujuzhuanxian1 : app + '/arcGis/image/map/logic/rnc1.png',
	shujuzhuanxian2 : app + '/arcGis/image/map/logic/rnc2.png',
	error : app + '/arcGis/image/map/nav_decline.png',
	//car : app + '/arcGis/image/map/1353402315_Order_tracking.png',
	car : app + '/arcGis/image/map/car-blue.png',
	people : app + '/arcGis/image/map/person.png',
	point : app + '/arcGis/image/map/TJpoint.png',
	station_red : app + '/arcGis/image/map/station_red.png',
	station_yellow : app + '/arcGis/image/map/station_yellow.png',
	station_green : app + '/arcGis/image/map/station_green.png',
	station_blue : app + '/arcGis/image/map/station_blue.png',
	yellow_pointer : app + '/arcGis/image/map/yellow_pointer.png',
	red_pointer : app + '/arcGis/image/map/red_pointer.png',
	blue_pointer : app + '/arcGis/image/map/blue_pointer.png'
};